[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.9"
log = "0.4"

xtask-waw = { git = "https://github.com/Marcel-G/waw-rs", features = ["wasm-opt"] }

