[package]
name = "sobaka-sample-audio-core"
version = "0.1.0"
authors = ["Marcel Gleeson <gleeson.marcel@gmail.com>"]
edition = "2018"

[dependencies]
dasp = { version = "0.11", features = ["all"] }
splines = "4.0"