pub mod clock;
// pub mod delay;
// pub mod envelope;
// pub mod filter;
// pub mod lfo;
// pub mod midi;
// pub mod noise;
pub mod oscillator;
// pub mod parameter;
// pub mod quantiser;
// pub mod reverb;
// pub mod sample_and_hold;
// pub mod sampler;
// pub mod scope;
// pub mod sequencer;
// pub mod step_sequencer;
// pub mod string;
// pub mod vca;
