name: "Backend"

on:
  push:
    branches: [master, next, feat/helia, feat/ipfs-cluster]
    paths:
      - 'backend/**'
  pull_request:
    branches: [master, next]
    paths:
      - 'backend/**'

jobs:
  build:
    name: "🧦 Build"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/ipfs/docker
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: backend/ipfs/docker
          tags: sobaka-kubo:latest
          outputs: type=docker,dest=/tmp/sobaka-kubo.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: sobaka-kubo
          path: /tmp/sobaka-kubo.tar

  infrastructure:
    needs:
      - build
    uses: ./.github/workflows/infrastructure.yml
    secrets: inherit

  deploy:
    name: "🏃‍♂️ Deploy"
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs:
      - build
      - infrastructure
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: ${{ needs.infrastructure.outputs.deploy_role }}
          role-session-name: DeploySession
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: sobaka-kubo
          path: /tmp
      - name: Tag and upload image to ECR
        env:
          ECR_REPOSITORY: ${{ needs.infrastructure.outputs.ecr_repository_ipfs }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker load --input /tmp/sobaka-kubo.tar
          docker tag sobaka-kubo:latest $ECR_REPOSITORY:$IMAGE_TAG
          docker tag sobaka-kubo:latest $ECR_REPOSITORY:latest
          docker push $ECR_REPOSITORY --all-tags
      - name: Deploy image to EC2
        run: |
          aws ssm send-command \
            --document-name "sobaka-backend-sobaka-next-ipfs-deploy-ipfs" \
            --instance-id "${{ needs.infrastructure.outputs.instance_id_ipfs }}" 

concurrency: 
  group: "${{ github.ref }}-backend"
  cancel-in-progress: true
